// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: kfeheivbgvzgvthpgdhp

class SupabaseConfig {
  static const String supabaseUrl = 'https://kfeheivbgvzgvthpgdhp.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmZWhlaXZiZ3Z6Z3Z0aHBnZGhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3NTE0OTAsImV4cCI6MjA4MDMyNzQ5MH0.CRFz5ZDA7SXnrshpYtsZH2EPtXUQ5YbmC8JBoS7YFgU';
}
